# Generated by Django 3.1.1 on 2020-09-05 20:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Порода')),
                ('code', models.CharField(max_length=256, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('describe', models.TextField(blank=True, verbose_name='Описание')),
                ('d_receipt', models.DateTimeField(verbose_name='Дата поступления')),
                ('kind', models.CharField(choices=[('1', 'CAT'), ('2', 'PARROT'), ('3', 'DOG')], max_length=3, verbose_name='Вид животного')),
                ('photo', models.ImageField(blank=True, upload_to='anim_photo', verbose_name='Фото')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Привит')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animal.breed', verbose_name='Порода')),
            ],
        ),
    ]
